# -*- coding: utf-8 -*-
"""escape character.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kZhPZqjNQ38rx6cBhoVrQAlaAvGcsqLk

escape character
"""

print ('dia berkata : "pergilah!"')

print ("aku menimpali: \"apakah kau ingin aku \'angkat kaki'?!\"")

print ("\\(^_^)/ (\\-_-/)")