# -*- coding: utf-8 -*-
"""materi  31-03-2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RDLddleeQ70BQs7Cf6rlxaXv27q4blqn
"""

nama = 'kholis rahmat habibi'
usia = 20
lajang = True

print(type(nama))
print(type(usia))
print(type(lajang))

usia = input('masukan usia anda')
print(type(usia))

a = 10/2
print(type(a))
b = 1/2
print(type(b))

kata = 'jeruk' * 5

panjang = input('masukan panjang')
lebar = input('masukan lebar')

print ('luas =',int(panjang) * int(lebar))

panjang = int(input('masukan panjang'))
lebar = float(input('masukan lebar'))

print ('luas =',panjang * lebar)

nama = 'wudoi'
tahun_lahir = 2000
print(nama + ' lahir pada tahun ' + str(tahun_lahir))