# -*- coding: utf-8 -*-
"""operasi in pada string.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZxU2CWugGH7atVOCC7iRZEe-oHjqGMMY
"""

berita = 'ramai-ramai developer di seluruh dunia mulai menggunakan \ teks editor masa kini seperti visual studio code, \ atom, sublime text, dan lain sebagainya.'
print('sublime text' in berita)
print('notepad++' in berita)

"""memotong string"""

nama = 'lendis fabri'
print(nama[0])
print(nama[1])
print(nama[3])
print(nama[4])
print(nama[5])

"""slicing string"""

judul = 'pelajaran matematika untuk SMA'
print(judul[0:5])
print(judul[:10])
print(judul[10:15])
print(judul[-1:-3])
print(judul[:31])
print(judul[-9:])

"""menghitung string"""

print(len('indonesia'))
print(len('arab'))

"""memeriksa karakter awal string"""

nomor_telepon_1 = '08123456789'
nomor_telepon_2 = '628123456789'
nomor_telepon_3 = '+628123456789'
kode_negara = '+62'
print(nomor_telepon_1.startswith('kode_negara'))
print(nomor_telepon_2.startswith('kode_negara'))
print(nomor_telepon_3.startswith('kode_negara'))

"""memeriksa karakter akhir string"""

email_1 = 'presiden@gmail.com'
email_2 = 'president@outlook.com'
print(email_1.endswith('gmail.com'))
print(email_2.endswith('outlook.com'))
print(email_1.endswith('outlook.com'))
print(email_2.endswith('gmail.com'))