# -*- coding: utf-8 -*-
"""string.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sjjp4FBE5hRnc0O8OzXZvJwf5QkicTvb
"""

template = 'halo, saya %s dari %s'
print(template % ('kholis', 'surabaya'))

template = 'halo, saya {nama} dari {asal}'
template_2 = 'saya suka makan {} dan minum {}'
print(template.format(nama='kholis', asal='jogja'))
print(template_2.format('nasi goreng', 'teh tawar'))

nama = 'kholis rahmat habibi'
asal = 'surabaya'
print(f'perkenalkan nama saya {nama} dari {asal}')

"""string split"""

alamat = 'surabaya, jawa timur, indonesia'
print(alamat.split())
print(alamat.split(','))
print(alamat.split(', '))

print('+'.join(['aku','suka', 'phyton']))
print('-'.join(alamat.split(',')))

print('alamat'.upper())
print('ALAMAT'.lower())

print('daun tidak pernah membenci angin'.title())
print('LASKAR PELANGI'.title())

print('índonesia Adalah Negara Kepulauan'.swapcase())
print('ÁKU CINTA negriku'.swapcase())

angka = '12345'
print('índeks angka 3:', angka.find('3'))
print('índeks angka 45:', angka.find('45'))
print('índeks angka 35:', angka.find('35'))

ibu_kota = 'jakarta'
print(ibu_kota.replace('a', 'i'))
print(ibu_kota.replace('a', 'i', 1))
print(ibu_kota.replace('a',''))

paragraf = 'baru-baru ini telah terjadi mogok makan di dunia'
x = paragraf.count('di')
print(f'kata"di" muncul sebanyak {x} kali')