# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QcFTtfCO0x7vvHhRdotrWsf_ynn4Gg6R

string
"""

nama = 'kholis rahmat habibi'
asal = "indonesia"

print(nama)

print(asal)

print(nama, asal)

print("nama saya :",nama)

print("nama saya:",nama)
print("asal saya:",asal)

data_lengkap = nama + asal
print(data_lengkap)



"""string+non string"""

asal_kota ="bandar lampung"
kode_pos = 35144

asal_kota_kode_pos = asal_kota + str (kode_pos)
print(asal_kota_kode_pos)

asal_kota_x3 =asal_kota *3
print(asal_kota_x3)

